all:
  vars:
    ansible_user: dgoldgar
    ansible_ssh_private_key_file: /home/dgoldgar/.ssh/homeassistant
  children:
    container:
      hosts:
        ansible-container:
          ansible_connection: local
          ansible_become: false
    mac:
      hosts:
        dgoldga-ltmpyaj:
          ansible_host: localhost
          ansible_connection: local  # Bypasses SSH for the local machine
          ansible_become: false      # Prevents sudo password prompt on local Mac
    pi:
      hosts:
        raspberry-slate: null
        raspberry-pearl: null
        raspberry-five: null
    ubuntu:
      hosts:
        ubuntu-one: null
        ubuntu-main: null
    thingino:
      vars:
        ansible_remote_tmp: /tmp/.ansible-${USER}
      hosts:
        camera-backdoor: null
        camera-catbox: null
        camera-catfood: null
        camera-driveway1: null
        camera-frontpath: null
        camera-frontdoor: null
        camera-frontporch: null
        camera-woodstove: null
        camera-aoqee1: null
        camera-aoqee2: null
        camera-aoqee3: null
        camera-aoqee4: null
