---

- name: Set hostname to inventory_hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure /etc/hosts has correct hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present
