- name: Ensure /opt/LITTERBOX/conf exists
  ansible.builtin.file:
    path: /opt/LITTERBOX/conf
    state: directory
    mode: '0755'


- name: Deploy decrypted secrets.yml to remote host
  ansible.builtin.copy:
    src: group_vars/all/secrets.yml
    dest: /opt/LITTERBOX/secrets.yml
    mode: '0600'
    backup: true
